### ISSUE TITLE
쇼핑몰 만들기 기본클래스,인터페이스 올려놨습니다.

### ISSUE THREAD

**Issue by LimJ2023** [LimJ2023/team-no-sigh#6]
올려놓은 shopingmall.zip

이 파일 받은 다음 저희 조건대로 구현해봅시다.

수정은 자유지만 웬만하면 너무 많이 바뀌지 않도록 하시고
천천히 하나씩 만들어 봅시다.

우리팀 과제 - 쇼핑몰 구현

(회원)
1. 회원가입
2. 회원 정보
3. 회원 정보 수정

(쇼핑)
1. 장바구니
2. 결제
3. 잔액, 포인트 계산

(쇼핑몰 정보)
1. 전체 매출
2. 재고 관리

회원 가입시 이름,전화번호 입력받아야함
가입할때마다 정해진 회원번호를 받음
(EX : 회원1=1001, 회원2=1002...)
회원은 처음 가입시 3000포인트 지급

일반 회원, 우수회원, vip회원의 세가지 종류 멤버 구현
일반회원 : 포인트 1% 적립
우수회원 : 포인트 5% 적립
vip회원 : 포인트 10% 적립, 10%의 가격 할인

**Comment by LimJ2023** [comment]
[shopingmall.zip](https://github.com/LimJ2023/team-no-sigh/files/13435783/shopingmall.zip)

**Comment by usernameljs** [comment]
![20](https://github.com/LimJ2023/team-no-sigh/assets/150655135/8cd2811d-8f0c-4e60-bbc9-7b8a47232220)

**Comment by maplesyrup0423** [comment]
천천히하겠습니다~
